@startuml
title JackInSpace

class CameraMover {
    - Camera targetCamera
    + void JackIn(Vector3 dstPos)
    + void JackOut()
}

class BezierCurve <<static>> {
    + static Vector3 QuadroBezierCurve(Vector3 p0, Vector3 p1, Vector3 p2, float t)
    + static Vector3 CubicBezierCurve(Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3, float t)
}

@enduml